### ISSUE TITLE
Video Location for RD130592 starts halfway through

### ISSUE THREAD

**Issue by jwolfski** [agrc/roads.utah.gov#41]
When the video starts to play for RD130592 the location does not start at the beginning of the road. I check the Video route on the database and it seemed to be okay on my end.

**Comment by stdavis** [comment]
This has been fixed in v2.3.5 and pushed to production. The issue was that the video points were not ordered chronologically in the database. I added a parameter to the query to make sure that they were ordered correctly and the issue was fixed. I'm surprised that we didn't run into this problem earlier. Please verify that it is fixed from your end.

**Comment by jwolfski** [comment]
Looks great on myu end. Thanks!

*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~**~~~*


[image: State of Utah]
Jason Wolf
*GIS Project Manager *

State of Utah  | Public Lands Policy Coordinating Office
m: 801.809.6340
w: publiclands.utah.gov
e: jasonwolf@utah.gov
a: 350 N State Street, SLC, UT
IMPORTANT: The contents of this email and any attachments are confidential.
It is strictly forbidden to share any part of this message with any third
party, without a written consent of the sender. If you received this
message by mistake, please reply to this message and follow with its
deletion, so that we can ensure such a mistake does not occur in the future.
